class Basket:
    #IN_CART = "//span[text()='1']"
    #CHOOSE_APT = "//div[text()='Сегодня - 1']"
    CONFIRM_CHOOSE_BUTTON = "//button[text()='Выбрать аптеку']"
    # LAST_NAME = "[data-test='lastName']"
    # ZIP = "[data-test='postalCode']"
    # CNT_BTN = "[data-test='continue']"
    # FINISH_BTN = "[data-test='finish']"
    FINAL_TEXT = "//h1[text()='Спасибо, заказ оформлен!']"
    FINAL_TEXT_LESS_50 = "//h4[text()='Минимальная сумма заказа 50 ₽']"
